### ISSUE TITLE
Paco Classifier documentation missing

### ISSUE THREAD

**Issue by malajvan** [DDMAL/Rodan#1061]
The Readme page of Paco Classifier is still a direct copy of the old Calvo Classifier. Since we removed Calvo Classifier and considering that Paco Classifier is an important job in Rodan that our lab members had work extensively on, we should at least write a short description for it.

**Comment by fujinaga** [comment]
@fjcastellanos Can you write a short description for this?

**Comment by fjcastellanos** [comment]
Hi, I've been comparing the Readme page of the Paco Classifier and the Calvo Classifier, and I see them as different. It is true that the first part is practically the same because they require the same configuration and used the same Rodan job to run. Also, it seems that Paco classifier includes some mentions to Calvo Classifier, but this is already deprecated. I'll fix that. The second part of the readme, which includes the parameters that can be configured, the use of scripts for local work, and the file structure, is new compared to the Calvo Classifier. 

I'm going to fix those mentions of the Calvo Classifier and add a brief introduction of the method.

**Comment by fjcastellanos** [comment]
Done.  I also removed the explanation of the ".sh" script that I made in the past for local training, as that file no longer exists in the repository.
