### ISSUE TITLE
[MEI encoding] - Obliques systematically missing their second component (rodan.staging)

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#1113]
Files coming out of an OMR workflow in staging have ligatures that look like this:

```
</syllable>
<syllable xml:id="m-026e8b36-b899-4afe-9430-da32b2528922">
       <syl facs="#m-cee5846c-76e9-4d92-86fe-137d2d512b52" xml:id="m-ea4f4145-6490-4c29-a974-66180e631cb8">cel</syl>
       <neume xml:id="m-402c5aa8-fcdf-40bc-833e-70c79c2e162b">
               <nc facs="#m-067bfd3c-7a75-4079-b8ae-d2ad9e3e80e2" ligated="true" oct="2" pname="g" xml:id="m-c1672cbd-ba4b-4508-b3dc-a90d791bd1fb"/>
       </neume>
</syllable>
```

The first neume component has a `ligated="true"`, which means it should also be followed by another neume component with the same attribute. Since it's not, ligatures aren't rendering properly and create much chaos in Neon.

The example file: [165v new staging test.mei.zip](https://github.com/DDMAL/Rodan/files/13564973/165v.new.staging.test.mei.zip)

**Comment by annamorphism** [comment]
So it sounds like the _real_ solution is to have MEI-encoding properly encode ligatures so they don't lose their other halves, which is what causes the "chaos" described by @JoyfulGen .
However, given that such encoding problems apparently do exist and are treated as valid MEI, perhaps Neon could check for ligated=true attributes without a matching pair and flag/remove them (or else make it so that the ligated=true attribute doesn't produce this behaviour, but that sounds harder...)

**Comment by JoyfulGen** [comment]
This doesn't happen anymore! Closing issue
