### ISSUE TITLE
OS for new Rodan production instance?

### ISSUE THREAD

**Issue by homework36** [DDMAL/Rodan#1138]
Last week, we booted the new instance from the old Rodan production volume (with all the old data), and it runs on Ubuntu 18.04. I personally feel that we should upgrade to a newer release since Ubuntu has stopped support for 18.04. However, according to Compute Canada, to do this we need to launch a blank new instance with that image. Therefore I have the following questions:
1. Do we want to do the upgrade now?  Since we are doing the migration now, this might be an easier time to change OS.
2. If we want to change OS, what do we want to use? Ubuntu 20, 22, or Fedora? 
3. In the case of creating a blank new instance, how should I set up the Rodan production server?

Because Wanyi is no longer in the lab, I don't feel confident to make all these decisions on my own, and there are many things I don't know. I would love to hear from people, especially @ahankinson. Thanks so much! 

Update on May 9: 

We currently have two VMs running, one for Ubuntu 18.04 and one for 22.04. I will try to deploy Rodan on Ubuntu 22.04 but will still keep the VM with Ubuntu 18.04 as a backup until the end of this month when we have lowered RAM.
I also tried Fedora but realized all our ansible config needs to be modified so I decided to keep Ubuntu for now.
As @timothydereuse suggests, I will now set up Rodan from scratch instead of using the old volume.

**Comment by ahankinson** [comment]
FWIW, the reason I have started suggesting Fedora is because Ubuntu is becoming a bit of a mess. I've had performance problems on DRAC with Ubuntu that I haven't run into with other distros, and I think it might be down to the virtual Hard Disk drivers they use in the Ubuntu image. But I haven't really been able to pin that down precisely.

Anyway, it's probably not a big deal if you use Ubuntu, but if it seems like things are really really slow, try it on another distro and compare it.

**Comment by homework36** [comment]
Due to docker support and vGPU driver limit by Arbutus, we can only use Debian 11 or Ubuntu 20/22 at this point.
We cannot do docker swarm successfully with Ubuntu 22 and Ubuntu 20 has not been tested because we cannot launch a new VM on arbutus now.
However, Debian 11 does work. A detailed documentation on how to set everything up will be added later.
