### ISSUE TITLE
Add Interactive Job check-out/check-in functionality

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/Rodan#213]
Currently it is possible that two people could take the same job and work on it, causing a human "race condition". We should add a flag to the runjob status that says that someone has checked it out and is currently working on it.

**Comment by lingxiaoyang** [comment]
Add two fields:

````
    - `working_user` -- a nullable field indicating the working user of an interactive
      job. If it is None, or the time is after the expiry time, there are no user working
      with this job.
    - `working_user_expiry` -- A datetime field indicating the expiry of `working_user`.
````

Rodan client should keep contact with server when the user is working on an interactive phase to keep locking the job to current user. There should be a Rodan setting indicating how many seconds a lock is effective, and Rodan should accordingly set `working_user_expiry` based on current time.

Rodan should respond success or failure for the locking request. Success should be given if `working_user` is None, or `working_user` is the same as current user, or `working_user_expiry` has been exceeded, and Rodan should respond with new `working_user_expiry`. Otherwise, if the locking fails, Rodan should respond with current `working_user` and `working_user_expiry`.

When an interactive phase is completed, `working_user` and `working_user_expiry` should be cleared.

For HTML-based apps, it may be necessary to use `<iframe>` to contain the interactive interface, and also monitor any page reloads or refreshes.

**Comment by lingxiaoyang** [comment]
The interactive interface view should refuse any requests if current user don't have the lock. This will force any client to implement the locking.

**Comment by lingxiaoyang** [comment]
The authentication of interactive interface should be token-based as it will be GET/POST-ing an HTML page. The token should also be in URL. This token, however, should be different from the token in token authentication that Rodan client uses, and should expire fast unless Rodan client keeps working on a runjob.

This token will be stored on `RunJob` model as `working_user_token`. URL will be `/interactive/{runjob_id}/{working_user_token}/`. If runjob ID and working user token match, and working user haven't expired, Rodan will authenticate the user in processing of the runjob.

**Comment by lingxiaoyang** [comment]
@mrbannon   There's a minor change in interactive run jobs. You'll need to acquire a token to "lock" the runjob before working on it.

Do you have interactive jobs in VIS now? If yes, how do you integrate these interfaces with your webapp? In Rodan test client, I have changed to use `<iframe>`s, and added one restriction on interfaces.
