### ISSUE TITLE
User uploaded file does not correspond to the selected resource type 

### ISSUE THREAD

**Issue by Ribu** [DDMAL/Rodan#359]
**Location: (Server), Type: (Bug), Priority: (High)**

Whenever I upload an image of type greyscale to the Rodan Test Client, even if I select image/greyscale+png as the resource type, after the uploading process is completed, the image is recognized as image/rgb + png. This prevents me from constructing a workflow that starts with jobs such as binarisation whose input port type is image/greyscale+png. 

**To clarify further**

Suppose that we have a Workflow 

![screen shot 2015-05-12 at 3 42 51 pm](https://cloud.githubusercontent.com/assets/7508527/7596714/c92b558c-f8bd-11e4-8a41-463c65167003.png)

Whose job consist solely of interactive binarisation 

![screen shot 2015-05-12 at 3 43 05 pm](https://cloud.githubusercontent.com/assets/7508527/7596737/f4645064-f8bd-11e4-9e89-2ac87ffc5315.png)

It is known from simple_binarise_interactive.py that the input type must be an image of type grey scale 

![screen shot 2015-05-12 at 3 47 13 pm](https://cloud.githubusercontent.com/assets/7508527/7596900/57b593b2-f8be-11e4-976c-661dfb029e7f.png)

Now given a grey scale image, and selecting image/greyscale+png as its resource type 

![screen shot 2015-05-12 at 3 50 12 pm](https://cloud.githubusercontent.com/assets/7508527/7596977/dc4376f8-f8be-11e4-816f-3f9bc4a61ef6.png)

After uploading, the image is labelled as img/rbg+png

![screen shot 2015-05-12 at 3 50 59 pm](https://cloud.githubusercontent.com/assets/7508527/7597039/54e25638-f8bf-11e4-87fd-85cf91a33756.png)

**Possible Cause**

Ryan further investigated in Rodan/rodan/jobs/core.py directory, and found that 
the particular segment of code below may be responsible for this bug

![screen shot 2015-05-12 at 3 59 58 pm](https://cloud.githubusercontent.com/assets/7508527/7597227/160184f6-f8c0-11e4-8a95-9ad4744ef9bc.png)

**Comment by lingxiaoyang** [comment]
It is the desired behavior. We once discussed whether the resource uploader could have full control of the resource type, and we thought no. For example, Rodan makes compatible files for image resources, and the types should always be image/rgb+png, to ensure it being recognized by Gamera.

And if you load with Gamera the compatible resource files that you just uploaded, you'll find the pixel format being RGB. You'll need to_greyscale job to generate a real greyscale type image.

And the resource type provided by the uploading API only applies to non-image files, because Rodan doesn't make compatible files for them.
________________________________
From: Rivu Khoda
Sent: 2015/5/12 16:02
To: DDMAL/Rodan
Subject: [Rodan] User uploaded file does not correspond to the selected resource type  (#359)


Location: (Server), Type: (Bug), Priority: (High)

Whenever I upload an image of type greyscale to the Rodan Test Client, even if I select image/greyscale+png as the resource type, after the uploading process is completed, the image is recognized as image/rgb + png. This prevents me from constructing a workflow that starts with jobs such as binarisation whose input port type is image/greyscale+png.

To clarify further

Suppose that we have a Workflow

[screen shot 2015-05-12 at 3 42 51 pm]<https://cloud.githubusercontent.com/assets/7508527/7596714/c92b558c-f8bd-11e4-8a41-463c65167003.png>

Whose job consist solely of interactive binarisation

[screen shot 2015-05-12 at 3 43 05 pm]<https://cloud.githubusercontent.com/assets/7508527/7596737/f4645064-f8bd-11e4-9e89-2ac87ffc5315.png>

It is known from simple_binarise_interactive.py that the input type must be an image of type grey scale

[screen shot 2015-05-12 at 3 47 13 pm]<https://cloud.githubusercontent.com/assets/7508527/7596900/57b593b2-f8be-11e4-976c-661dfb029e7f.png>

Now given a grey scale image, and selecting image/greyscale+png as its resource type

[screen shot 2015-05-12 at 3 50 12 pm]<https://cloud.githubusercontent.com/assets/7508527/7596977/dc4376f8-f8be-11e4-816f-3f9bc4a61ef6.png>

After uploading, the image is labelled as img/rbg+png

[screen shot 2015-05-12 at 3 50 59 pm]<https://cloud.githubusercontent.com/assets/7508527/7597039/54e25638-f8bf-11e4-87fd-85cf91a33756.png>

Possible Cause

Ryan further investigated in Rodan/rodan/jobs/core.py directory, and found that
the particular segment of code below may be responsible for this bug

[screen shot 2015-05-12 at 3 59 58 pm]<https://cloud.githubusercontent.com/assets/7508527/7597227/160184f6-f8c0-11e4-8a95-9ad4744ef9bc.png>

**Comment by Ribu** [comment]
Thanks for the clarification. Just one more question though...

The image that I am uploading is a real greyscale type image that I have generated through GreyScale Job. 

For example, prior to doing the just_Binarise workflow, I have setup a workflow 

![screen shot 2015-05-13 at 10 09 04 am](https://cloud.githubusercontent.com/assets/7508527/7612463/fe0a4ad8-f958-11e4-91c8-fa7b4380ac80.png)

whose job is simply to greyscale any uploaded image 

![screen shot 2015-05-13 at 10 09 16 am](https://cloud.githubusercontent.com/assets/7508527/7612472/136596c6-f959-11e4-8f61-bf0a11b875ee.png)

So once the image is uploaded and the workflow is processed 

![screen shot 2015-05-13 at 10 09 58 am](https://cloud.githubusercontent.com/assets/7508527/7612503/4bcbb0fe-f959-11e4-82a7-35f6bf06af73.png)

I then download it and check to see if the pixel format is indeed greyscale 

![screen shot 2015-05-13 at 10 10 16 am](https://cloud.githubusercontent.com/assets/7508527/7612513/5ac2527a-f959-11e4-8cac-27318890a452.png)

![screen shot 2015-05-13 at 10 13 16 am](https://cloud.githubusercontent.com/assets/7508527/7612521/61f5455c-f959-11e4-94e2-374e4caa9aee.png)

![screen shot 2015-05-13 at 10 13 36 am](https://cloud.githubusercontent.com/assets/7508527/7612530/746a9ca0-f959-11e4-8950-340650c74d01.png)



![screen shot 2015-05-13 at 10 10 16 am](https://cloud.githubusercontent.com/assets/7508527/7612513/5ac2527a-f959-11e4-8cac-27318890a452.png)

This image is then uploaded and the resource type is being selected as img/png+greyscale. However, as I previously mentioned, it gets recognized as image/png+rgb. Therefore, I cannot use workflow that  consists solely of binarasation as it expects an image of type greyscale.

In any case, if this is the desired behaviour then that's great !

**Comment by lingxiaoyang** [comment]
https://github.com/DDMAL/Rodan/blob/develop/rodan/jobs/core.py#L48

The image is converted to RGB pixel type after uploaded. It is because we don't expect an end user to distinguish different pixel types of images. That's partially why we do the image type conversion. On the other hand, if the format of an image is not recognizable by Rodan, we would like it to fail in the resource uploading process (the conversion is not successful and there is an error), instead of failing a runjob in the future.
