### ISSUE TITLE
Project/Workflow and Resource Sub-Collections

### ISSUE THREAD

**Issue by magoni** [DDMAL/Rodan#367]
The `/project/:uuid` route currently returns two resources not included within the collection returned by `/projects/`: the `workflows` and `resources` sub-collections (arrays).

1. Should these sub-collections remain available at `/project/:uuid`? If an API consumer wants to get workflows associated with a project, should they hit `/workflows/?project=uuid` instead of accessing the `workflows` sub-collection at `/project/:uuid`?

2. The `workflows` and `resources` arrays are not paginated, meaning that the `/project/:uuid` response is very large for projects with lots of resources.

3. Should the entries in these arrays have `uuid`s? Currently they only have `url`s.

**Comment by ahankinson** [comment]
1. If the response is very large, we could pare it down to just URL and name for both workflows and resources. That way we can display a list, and clicking on the name will load the actual data.

2. The workflow/resource data in /project/:uuid cannot be paginated, so just name/URL is OK.

3. URLs are preferred over plain UUIDs, so my vote is "no."

**Comment by lingxiaoyang** [comment]
1 -- I tried returning name/URL only. The response size is acceptable but it sill takes a long time to query the sub-collections in database (especially in the case where a project has a lot of resources).

I think we may need database optimization. Or does it make sense to let the /project/:uuid return user-uploaded resource only? (instead of generated resources)

**Comment by lingxiaoyang** [comment]
A live example at the moment: http://rodan-dev.simssa.ca/project/6b29d382525e4151b5ea85825b648757/

**Comment by ahankinson** [comment]
OK:

https://docs.djangoproject.com/en/1.8/topics/db/optimization/
https://docs.djangoproject.com/en/1.8/topics/performance/

Profile first! 

https://github.com/mtford90/silk/

The Django Debug Toolbar can be useful in seeing what the actual queries are so that indexes can be added if necessary.

We may want to switch to uWSGI if it's the CGI interface that's slowing it down.

http://www.peterbe.com/plog/fcgi-vs-gunicorn-vs-uwsgi
https://www.digitalocean.com/community/tutorials/django-server-comparison-the-development-server-mod_wsgi-uwsgi-and-gunicorn

**Comment by lingxiaoyang** [comment]
Note I removed workflow/resource count, as you now have the entire list and can count yourself in client.
