### ISSUE TITLE
Store workflowjob coordinates on server

### ISSUE THREAD

**Issue by lingxiaoyang** [DDMAL/Rodan#377]
The client needs the coordinates for displaying the workflow properly. But the coordinates may not be a part of Rodan server. Think about a "plugin" manner to implement this feature.

**Comment by ahankinson** [comment]
I think we should have a model with four fields: Workflow ID, WorkflowJob ID, pixel co-ordinates, and a type of client (RodanClient, Mobile App, etc.). A client can query this model for any matching workflow layouts and apply them.

**Comment by mrbannon** [comment]
I'm not sure how I feel about this. (Granted, Rodan is not my "baby", but I
feel as though I should make my argument.)

To me, the Rodan model is just for describing workflows. That's it. Adding
specific models for something that does not directly facilitate the
workflow feels as though it doesn't belong. But, more importantly, it would
create a precedent that opens up future modifications to the Rodan model.

Having said that, here are my ideas for alternatives:

1) A Rodan plugin system

I believe this was your original idea, and I still think it's the best. A
plugin system allows Rodan to keep the workflow model intact while being
flexible enough to leverage other development ideas (not just for GUI
coordinates).

I suppose the plugin system would need the following:

- a small set of REST calls
- a single, generic model that stores data for plugins and associates them
with a single Rodan model

The plugin data model would be defined as follows:

*PluginData*
*- uuid*
*- associated plugin ID (that is, each instance of each model must be
associated with an installed plugin)*
*- associated Rodan model (plugins "enhance" the Rodan model, so we need to
associate them with Rodan models)*




*- data (this is simply text data, or JSON, or whatever; Rodan doesn't
care, really)- creator- created- updated- context*

*context* is simply a string ID that helps further distinguish multiple
instances of *PluginData*. I imagine this could come in handy to
distinguish data in the same plugin that is associated with the same Rodan
data. For example, a Rodan client could have two versions - one desktop and
one mobile - that have different coordinates associated with it. Both
versions of the client could easily use the same plugin.

2) Client connects to a separate server to get data

This is pretty much the same as above, only it's out of Rodan's hands. On
the plus side, we wouldn't have to worry about developing a plugin system.

I have plenty more to say, but maybe it's better to discuss in person.

**Comment by ahankinson** [comment]
My worry is that with all these extra bits (plugins, jobs, etc.) we're over-engineering.

A plug-in should be reserved for things that are optional functionality. Making a whole plug-in system just for this one bit of functionality, just because we want to keep the core "pure" reeks of over-engineering to me.

If we build a plug-in system we have to document it and explain the difference between it and jobs, which are like plugins, but different. 

On top of this, we'll probably want fancy things like auto-discovering plugins, a plug-in registry, blah blah blah. I have no interest in doing this.

On the other hand, we could very easily a model, view, and routes to the existing core with little extra engineering overhead. It may not be the "purest" solution, but it would work, and work well.

**Comment by mrbannon** [comment]
Thinking about it again, the engineering required to develop a "plugin"
system wouldn't be any more difficult than creating models for GUI data
storage. (I put "plugin" in scare quotes because I don't see it as a true
plugin anymore.)

All that we're doing is creating a a model to store some kind of data. If
it's truly geared towards storing GUI data, then the model is very
precisely defined. However, if we developed a model to store generic data,
then it could be leveraged to store any kind of information for a workflow,
including GUI coordinates. (I imagine that the data it stores is simply
JSON data.)

**Comment by lingxiaoyang** [comment]
@mrbannon    You can have a test on it using branch `gui-coordinates`. After checking it out, you'll need to update the database:

``````
python manage.py makemigrations
python manage.py migrate
``````

**Comment by mrbannon** [comment]
Tx!

**Comment by ahankinson** [comment]
Fixed in ce18ce81b7b666c6fb914d67ea78fc2b4211cc86?

**Comment by lingxiaoyang** [comment]
@ahankinson    Yes, I tested it locally. Ryan will test it later.
