### ISSUE TITLE
Inconsistent field inclusion between lists and single object

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#410]
If you look at the following:

http://132.206.14.136/inputport/aad996db-897d-4a20-9940-181dd82e905a/

You'll note that the field 'workflow_job' is present. However, when InputPorts are listed within WorkflowJobs:

http://132.206.14.136/workflow/0d11ca8d-db56-404b-b189-c67c69f549b1/

The 'workflow_job' field is not there. As a general rule, I believe all simple data types should be included in returns (for consistency).

**Comment by lingxiaoyang** [comment]
We might have removed `workflow_job` deliberately because of circular references... I'll test later.

**Comment by lingxiaoyang** [comment]
@mrbannon  There are not circular references. I may need your opinion on the retrieval of Rodan objects as there're a lot of relations. As for your example, the "Workflow" view goes deeper into WorkflowJobs and their InputPorts and OutputPorts, and it is for easier retrieval -- otherwise, the client will have to GET every object tracing the hyperlinks... which will incur additional cost of HTTP requests. 

I agree that the field inclusion should be somehow consistent, Right now we may have different set of fields between a xxxList view and xxxDetail view (Projects vs Project). And the set of fields may be different if it appears as a nested object (like in your example). Which level of consistency do you expect to make things easier on the client side?

**Comment by mrbannon** [comment]
Let's talk about this tomorrow after the meeting.

**Comment by lingxiaoyang** [comment]
There's still inconsistency in Project serializers. The workflows and resources in the info of a Project are shown as list of (url, name), while you'll get all fields when you retrieve workflows and resources directly. Is it the correct behaviour?

**Comment by mrbannon** [comment]
That's fine.
