### ISSUE TITLE
Disable auto-conversion of image files

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Rodan#413]
Right now an image uploaded to Rodan automatically goes through conversion to PNG. If this job packages is NOT installed in Rodan, Rodan still tries to do it. This causes the 'compat_file' field of the associated Resource to be empty, therefore the Resource cannot be used.

This behaviour should probably be removed as it is up to the Workflow designer as to how the Resource should be processed.

**Comment by lingxiaoyang** [comment]
It's right. Other configurations of Rodan should not depend on image processing packages.

The automatic conversion was originally there because we wanted to handle different types of PNGs in Gamera and let images to be of RGB pixel type by default. 

But, if we remove automatic conversion, the user has to clearly specify the type of images... which the user may not know. (For example, the user may think an image to be GRAYSCALE but it is actually of RGB pixel type.) We may need to restrict what the user can do when they add new resources in the future...

**Comment by mrbannon** [comment]
I agree. Ideally, Rodan will have auto-detect methods at a later date. This could be part of a job package. For example, job packages could include a special Rodan task that reads in a file and determines if it is of a particular type. OR, Rodan could guess based on file extension.

Either way, disabling the auto conversion is a first step.

**Comment by Nicky666** [comment]
fixed in noImageProcessing branch

**Comment by mrbannon** [comment]
Awesome!
