### ISSUE TITLE
Libmei version inside of Rodan is unstable and should be updated to 3.0

### ISSUE THREAD

**Issue by noahbaxter** [DDMAL/Rodan#473]
The internal version of Libmei/Pymei is currently unstable. Many python bindings do not correspond to the correct c++ bindings, leading to a series of crashes and errors. During crashes, the traceback points to seemingly random lines, often to completely unrelated code, or even to comments and newlines with no functionality at all. This library should be fixed and updated to the latest version 3.0 to both add necessary support for Python 3 and to ensure stable use of the library.

**Comment by vigliensoni** [comment]
Since you are using the libmei version installed in the RODAN docker container, I think this issue should be part of https://github.com/DDMAL/rodan-docker

You may want to request to update the submodule linked in https://github.com/DDMAL/rodan-docker/tree/08fbf382e56ef15ff296bdf07f924969c71c7626/rodan/code/external

Am I right @deepio ?

**Comment by deepio** [comment]
In a way, you're both correct. Because things that have changed in libmei should be tested with the latest version of all other rodan jobs that use it, prior to implementing it. Installation instructions, if they are different, also would need to be updated in rodan-docker.

**Comment by noahbaxter** [comment]
Turns out this was a python 2 issue, because MeiElement (and most pymei functions) are expected as strings and not unicode variables in python2. Simply casting variables as strings solves this problem. https://github.com/DDMAL/JSOMR2MEI/issues/3
