### ISSUE TITLE
[MEI Encoding Job] MEI output with <syllable> elements that have a <syl> but no <neume>s

### ISSUE THREAD

**Issue by timothydereuse** [DDMAL/Rodan#629]
See: https://github.com/DDMAL/Neon/issues/800. 

![image](https://user-images.githubusercontent.com/28409383/167063221-b8611ca6-c9ef-4a30-8332-6604bc8f9b0b.png)

I expect this occurs when a syllable is recognized in the text but no neumes are found above it. Fix by filtering out any syllable elements that have no neumes in them near the end of the process.

**Comment by JoyfulGen** [comment]
Small edit: that screenshot is actually of something else! This is what the empty syllable looks like in MEI:

<img width="662" alt="050r empty syl SOOMR" src="https://user-images.githubusercontent.com/83373378/167876155-f81e0dee-d7b3-49bc-82f5-2f50c85dee6f.png">

**Comment by sabrina0822** [comment]
Looking into fixing this in the mei encoding job. Removed all empty syllables except the ones in situations like these: 

<img width="496" alt="image (1)" src="https://user-images.githubusercontent.com/90227881/168836493-21e7999a-0765-4cf8-940f-b7815ec294b9.png">

Since the clef needs to be pulled out of the syllable layer we are left with something that looks like this: 
![image (2)](https://user-images.githubusercontent.com/90227881/168836592-002464b7-49ad-4be9-b79c-d92465f2aca8.png)

@annamorphism @JoyfulGen do you think the empty syllable here should be kept? I can delete it smoothly I'm just not sure if this is information we would want to keep.

**Comment by JoyfulGen** [comment]
@sabrina0822 I think the problem here is that the empty syllable in question contains the `syl`, so deleting it would mean that the remaining syllable after the clef wouldn't have one. I've had an idea for a slightly different solution that I think would make more semantic sense and remove this issue: 

When removing a clef/custos/sb from a syllable, if that clef/custos/sb is before any neume in the syllable (so like in the syllable above), rather than split the syllable at that point, move the newly extracted clef/custos/sb to before the beginning of that syllable. Then you keep the syllable together without having to use `precedes` or `follows` attributes and it's less work for the correcter. If there *is* a neume before the clef/custos/sb, then the above fix will work!
@annamorphism do you agree?

**Comment by annamorphism** [comment]
@JoyfulGen I agree that that should work!
