### ISSUE TITLE
[MEI Encoding Job] Rewrite entire job without LibMEI dependency, in Python 3 

### ISSUE THREAD

**Issue by timothydereuse** [DDMAL/Rodan#630]
The LibMEI / pyMEI library is difficult to install in Python 3. To move Rodan away from Python 2, we need to rewrite this job, preferably using the built-in XML manipulation tools in Python (ElementTree). The logic of how the MEI is encoded can remain the same.

**Comment by sabrina0822** [comment]
Update: still working through some bugs, the precedes and follows attributes for syllables get a little messed up when deleting empty syllables (they point to nothing). Also when there are multiple elements that need to get pulled out of a syllable back to back there are some complications (i.e. syllable, some neumes, two custodes in a row, more neumes, closing the syllable). 
I think this has to do with the way I implemented pulling elements out of syllables.
Should get this working within the next day or so.

**Comment by sabrina0822** [comment]
Completed and merged. To sum up all major fixes @timothydereuse 
1. MEI Encoding no longer uses LibMEI to create the MEI files, instead it uses python element trees!
2. Updated to MEI version 5 dev --> now all custodes, clefs, accidentals, and line breaks are placed outside of the syllable.

Since more elements were being pulled out I had to implement a new algorithm to make the MEI file as simple as possible. 
Basically, the build_mei function now uses a dictionary that stores the current syllable. It will not add this syllable to the MEI file **until it comes across a neume**. This was done to prevent unecessary precedes and follows attributes for empty syllables. 

_So a syllable that used to look like this:_ 
```
<syllable>
     <syl>
     <clef>
     <neume>
         ...
      ...
<\syllable>
```
_becomes_ 
```
<clef>
<syllable>
     <syl>
     <neume>
          ...
     ...
<\syllable>
```

This also applies for divLines that occur in a syllable before a neume (they are taken out and placed before the syllable). Normally, however, divLines are placed within the syllable. 

Additionally, to account for all the elements being pulled out of syllables there are now precedes and follows attributes that link together syllables separated by an accidental/custos/sb/clef.
_Before:_ 
```
<syllable xml-id:12345>
     <syl>
     <neume>
         <nc>
      <\neume>
     <accid>
     <neume>
         <nc>
         <nc>
      <\neume>
<\syllable>
```
_becomes_ 
```
<syllable xml-id:12345 precedes:67890>
     <syl>
     <neume>
         <nc>
      <\neume>
<\syllable>
<accid>
<syllable xml-id:67890 follows:12345>
     <neume>
         <nc>
         <nc>
      <\neume>
<\syllable>
```

Finally, fixed the empty syllable problem by removing all syllables that contain only one child (that is a syl). This is done with a function that goes through the MEI file at the end of the process. 
So all syllables that look like this would get removed.
```
<syllable>
     <syl>
<\syllable>
```

Some time later this summer I will try to come back to the MEI encoding job as I have some ideas of how to make the code less repetetive and decrease the number of if statements in the build_mei function. There is still the issue with the 0,0,0,0 bounding box that Gen posted a couple of weeks back that also needs to be fixed.
