### ISSUE TITLE
Python environments should be defined in a single requirements.txt file for each Celery image

### ISSUE THREAD

**Issue by timothydereuse** [DDMAL/Rodan#639]
Currently, the Python environment inside each Celery image is defined in [Each of the 'install_*****_rodan_jobs'](https://github.com/DDMAL/Rodan/tree/develop/scripts) scripts by sequentially installing the contents of each `requirements.txt` folder for that particular image. This is a holdover from when all the jobs were in their own github repositories, and is difficult to maintain.

Every image we maintain that has its own python environment should have its own `requirements.txt`, located in the same directory as its dockerfile. These should not be written to by people who are working on jobs - they should conform to what the environment dictates. These requirements files could be generated by simply performing a `pip freeze` inside every docker container, and then rewriting the `install_*****_rodan_jobs` scripts accordingly.

**Comment by sabrina0822** [comment]
Update: Now that we have updated all jobs to python 3 I am merging all python 3 updates into the requirements_dev branch and will clean up everything and fix this issue.

**Comment by EMZEDI** [comment]
@timothydereuse I guess this issue is solved and can be closed?

**Comment by p42ul** [comment]
@EMZEDI not quite. We still have `requirements.txt` files scattered around, for the time being.

https://github.com/bndr/pipreqs may be a helpful tool for consolidating our dependencies.

**Comment by sabrina0822** [comment]
To summarize what I discussed with @timothydereuse 
It's possible to create one requirments.txt file only if we either get rid of calvo's method or find a way to have calvo's and paco's requirements not contradict each other. We discussed getting rid of calvo's a while back but since some people still use it, I don't think that should be done for a little while.

**Comment by malajvan** [comment]
Ich agreed to remove Calvo's methods. Will clean this up and finish this requirements.txt files

**Comment by softcat477** [comment]
We might have difficulties doing so in `gpu` container. `paco`, `sae binarization`, and `background removal` are in separate repo installed with `setuptools`. They are meant to be installed and used as python packages and have their own requirements.txt in their repos.

**Comment by sabrina0822** [comment]
When I pip freeze in the gpu container this is what is currently installed (modified the output to remove irrelevant requirements): 
```
h5py==3.1.0
keras==2.5.0rc0
numpy==1.17.3
opencv-python==4.6.0.66
opencv-python-headless==4.1.2.30
scipy==1.7.3
six==1.15.0
tensorflow==2.5.1
```

**Conflicts:** 
Paco classifier's requirements: 
```
numpy==1.19.2
opencv-python==3.4.2.17
```
Outside of paco's requirements.txt file there are some dependencies outline in the documentation that conflict with what we have in the gpu container: 
```
h5py (2.7.0)
Keras (2.0.5)
scipy (0.19.1)
six (1.10.0)
Tensorflow (1.5)
opencv-python (3.2.0.7)
```
I'm not sure if these are minimum requirements though or the exact version we need @softcat477?

SAE Binarization: 
```
numpy==1.19.2
opencv-python==3.4.2.17
```

Background removal: 
```
opencv-python (3.2.0.7)
```

Text allignment: 
```
scipy; python_version > "3.4"
```

At the end of installing all of the gpu jobs in the `install_gpu_jobs` script we have this line
`pip install opencv-python==4.6.0.66` which is what is causing all the opencv conflicts but was added so the images could build from what i remember?

**scipy, six, h5py conflicts could be caused by calvo classifier so I'm going to first remove that from rodan and then see what conflicts remain.
