### ISSUE TITLE
progress not saving in Rodan

### ISSUE THREAD

**Issue by carrieeex** [DDMAL/Rodan#651]
When we were correcting Neon within Rodan, saved it and closed the tab, it was not saved in Rodan, as when we opened the Neon in "Run Jobs" in Rodan, it reverted back to the original one, rather than the one we just corrected. This also happens to Interactive Classifier in Rodan (https://github.com/DDMAL/Interactive-Classifier/issues/223).

**Comment by malajvan** [comment]
Currently the work around for this issue is you validate your current work and let Neon generate the new MEI files, which you can then reupload onto Rodan and Neon to continue your work. We'll close this for now since the save function is intended for standalone use. We'll reopen if this feature is requested again.
