### ISSUE TITLE
Make "ImageZipper" Job that takes in multiple images and outputs them as single zipped file

### ISSUE THREAD

**Issue by timothydereuse** [DDMAL/Rodan#674]
This is for use in Paco's document analysis method in future; we need a job that has a variable number of input ports, all of the same type (`png+rgb`, or whatever Paco's method uses as input), and a single output port. The job just takes all of its inputs, zips them (or puts them into a `tar.gz` file, whatever's easiest in Python - doesn't really matter which), and outputs the zipped file.

It will be necessary to add the resulting filetype as a valid resource type so that Rodan recognizes it and so that Paco's method can accept files of that type.

**Comment by EMZEDI** [comment]
UPDATE: Finished the job.
1. There is no need to have a Rodan job for this task because the Rodan jobs don't guarantee the order of the input files. 
2. A desktop app is designed for both Windows and MacOS to zip a set of files or a directory with specific extensions.
3. The repository and guide to download the application is here: [LINK](https://github.com/EMZEDI/ImageZipper)
4. Tested by the Document Analysis team, the task works and for further production usage, the desktop app can be downloaded via a link in Rodan production.

**Comment by EMZEDI** [comment]
🎨 Done! PR # 56 in pixel wrapper repo!
