### ISSUE TITLE
3 OMR functions performing less well (May to October comparison) - 1/3 BOUNDING BOXES

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#802]
This is one of three issues related to a significant change in OMR performance between May and October 2022.
2/3 Pitch finding: https://github.com/DDMAL/Rodan/issues/944
3/3 Syllables: https://github.com/DDMAL/Rodan/issues/945

This is the original issue written that mentions all three changes, but the solutions down below pertain to the bounding boxes.

I've noticed that in recent OMR runs, the pitches are almost systematically too low and the syllables are too few and too big. To test this theory, I ran Einsie folio 129r yesterday (October 27) to compare the result to my initial processing of the same folio on May 30. Here's a comparison of the results with the neume highlight (I only resized the staves to make the pitches easy to see; I made no other changes):

<img width="1415" alt="Neumes comparison 129r" src="https://user-images.githubusercontent.com/83373378/198675657-b772e31c-5bcf-4276-98c7-1cdd2e71b82a.png">

You can see that, indeed, the pitches are generally more off in the recent folio. There also appear to be more glyphs in the "gutter."

Here's a comparison of the results with the syllable highlight:
<img width="817" alt="Syllables comparison 129r" src="https://user-images.githubusercontent.com/83373378/198675841-64b2ae4d-9160-4c57-9dcf-6639c5425d73.png">

Here, you can see that the syllables in the recent folio are generally too big. There are also parts of the text missing and some syllables are empty right off the bat.

These are the two MEI files, as well as the original folio image:
[129r now.mei.zip](https://github.com/DDMAL/Rodan/files/9889843/129r.now.mei.zip)
[129r then.mei.zip](https://github.com/DDMAL/Rodan/files/9889844/129r.then.mei.zip)
![Einsiedeln__Stiftsbibliothek__Codex_611_129r](https://user-images.githubusercontent.com/83373378/198676093-ec6b8ac8-998f-4280-be78-224beb9c9065.jpg)

This is not a problem that's actually hindering correction, but it is making it significantly longer, because there's much more to correct.

**Comment by timothydereuse** [comment]
A few questions:

Are you using the exact same models for the layer classification (i.e. Calvo) as you did back in May?
Are you using the exact same workflow as you used to? Any added jobs (even small ones like image conversions)?
Is the classification of symbols different? (I.e. is the behavior of the interactive / noninteractive classifier different - are clefs getting misclassified as neumes whereas they used to be classified correctly, etc)

Could you also attach the inputs to the MEI encoding job from the most recent one? I feel like the problem might be there, because that's the only job that's had significant changes to its functionality, but I am not sure.

**Comment by JoyfulGen** [comment]
A few answers (in order):

Yup, same models.
Same workflow, no added jobs.
From what I can tell, the classifications of symbols is identical. It's just pitch and syllabification that have changed.

I can't get the MEI encoding job inputs just now, because I'm running a big ol' job for MS73, but I'll add them to this comment as soon as I can.

**Comment by annamorphism** [comment]
Just saw this issue today. @timothydereuse did anyone ever get to the bottom of this? These errors can all be corrected in Neon, but it would be nice not to have to...

**Comment by JoyfulGen** [comment]
So sorry, I said I'd update the issue and fully forgot! Here are the inputs for the MEI encoding job for folio 056v.

[056v pitch finding.json.zip](https://github.com/DDMAL/Rodan/files/10167127/056v.pitch.finding.json.zip)
[056v text alignement.json.zip](https://github.com/DDMAL/Rodan/files/10167128/056v.text.alignement.json.zip)

**Comment by MrMondrian** [comment]
This issue has been solved. This folio is more rotated than the healthy test cases. When rotating the bounding box, the axis of rotation is not considered and uses the default of the top left corner instead of the middle.

My theory for why this error started showing up instead of always being there is maybe the person in charge of photographing einsie started off strong making every picture perfectly straight, but as they progressed their picture taking became more and more lazy. The earlier folios would then not need to rotate the bounding boxes, hiding the bug. But the later folios would be slightly skewed, which breaks the bounding box code.

@JoyfulGen Does this theory line up with your findings, and do you think it's likely?

**Comment by annamorphism** [comment]
I'm still not clear on why the same folio performed less well with the later MEI encoding job--was some sort of rotation spec introduced in summer of '22? 
I'm a little skeptical of the conclusions here, because if anything this page has less outright rotation than some of its earlier friends--the very earliest folios have a decided slant in the staff lines from upper left to lower right (on the recto, and vice versa on the versos) that disappears toward the middle of the book. This particular folio *is* a little more three dimensional than most--there's a wrinkle in it that means the lines on it are not very parallel when projected onto our screens.  This is pretty common--on the whole the Einsie picture are much, much flatter and straighter than many other examples!--so it's worth documenting pretty explicitly how this is or isn't taken into account in the job in question.

**Comment by MrMondrian** [comment]
Oh I wasn't aware of that. The thing is, looking at the code I'm not sure why the bounding boxes ever worked. Maybe there was code that did the rotations properly but got removed for some reason? I'd have to sleuth the commit history to find out. It's actually quite possible that rotate bounding boxes code was reverted because the function was taking the pivot as an argument but wasn't using it for anything

**Comment by JoyfulGen** [comment]
@MrMondrian I agree with @annamorphism; I compared the performance for the same folio, so there's no rotation difference to account for the worse performance. Also, that doesn't explain why pitch finding is also performing less well. Can I reopen the issue?

**Comment by MrMondrian** [comment]
@JoyfulGen was the pitch finding part of this issue ever resolved?

**Comment by MrMondrian** [comment]
No one had bounding box issues in the last round of E2E so I'm closing this issue. Please reopen if the error occurs again.

**Comment by JoyfulGen** [comment]
I just tested this by running an e2e of 195v to compare it with a one I did in December 2022. These are the two folios side by side, old one on the left:

<img width="1127" alt="195v old vs new BBs" src="https://github.com/DDMAL/Rodan/assets/83373378/834db19d-271d-4e27-981f-e664b94b8c01">

**Comment by JoyfulGen** [comment]
**UPDATE**: please disregard the above data, turns out I was using the wrong model and also not all changes were pushed to production, so I shall test again and return.

**Comment by JoyfulGen** [comment]
**New Update**: I ran the original folio (129r) again on staging with the correct text alignment model and the bounding boxes are much improved!!

<img width="958" alt="129r new! bbs" src="https://github.com/DDMAL/Rodan/assets/83373378/e71bc558-4398-432a-a641-fbd70c864b1c">

 @MrMondrian very sorry for the false alarm
