### ISSUE TITLE
[MEI Encoding] Incorrect Custos Notes

### ISSUE THREAD

**Issue by sabrina0822** [DDMAL/Rodan#888]
Sometimes the notes of custodes do not match the note of the next neume. This does not make sense since custodes by definition are supposed to indicate where the first note on the next staff is supposed to be. 

It would be beneficial to fix this in the MEI Encoding job by ensuring the note of a custos is the same as the note of the next neume. This can either be done in the build_mei_function as file is being built or at the end when all empty syllables are being removed.

**Comment by yinanazhou** [comment]
@jackyyzhang03 thank you for your propose. But this feature is beyond the intended scope of Neon. 

> 3. My opinion is that MEI encoding should only encode data into MEI, as corrections are the responsibility of Neon.

Neon is an editor, not a corrector. Neon provides correction choices for users, but does not do any corrections itself. The MEI encoding job is a job in the automated OMR process, so it could have the ability to do rule-based checks and corrections.

> 2. Neon already uses Verovio which we can leverage to update the positions automatically by simply setting the pitch attribute.
> 4. This could help [#1005](https://github.com/DDMAL/Neon/issues/1005) which also needs a way to update pitches through Verovio.

As mentioned earlier, Neon should not have the ability to automatically do anything without an action from the user. As for verovio, it updates the pitch based on the positions edited by the users now. It might be confusing and not optimal if we create a new in verovio the other way around, as the main function of verovio is to render MEI elements into SVG elements based on the position provided by the MEI file. The arrow key pitch updating feature may not need a new verovio action (still in discussion). It can be done by dragging the element by half staff size, which is also position-driven.

> 1. In MEI encoding, we could correct the pitch, but we would not know how the bounding box for the custos should be adjusted, so the custos would still appear in the wrong position in Neon.

For this concern, since the position of an element is based on the score, I would suggest to check if the position is changed somewhere in the OMR process. Theoretically, the position should be correct, but we need to verify this. 

> We could add an option in the MEI Actions dropdown for this, or a button somewhere else.

This is possible, but I would leave this as the last option.

Please let me know if you have any questions.

**Comment by jackyyzhang03** [comment]
I've implemented the changes in MEI encoding. However, the existence of extra notes from the previous page causes the assigned pitches to be incorrect. Is this something that should be considered in this ticket?

![Screenshot 2023-05-18 at 4 15 57 PM](https://github.com/DDMAL/Rodan/assets/81784897/5e35e85f-c420-44c6-a178-315747c11598)

**Comment by yinanazhou** [comment]
What about finding the first neume component after the clef?

**Comment by jackyyzhang03** [comment]
> What about finding the first neume component after the clef?

That is a nice idea and something I was also wondering about. I was going to bring it up in the lab meeting since I am not 100% sure if a clef always follows a custos, though I imagine it usually does.

**Comment by JoyfulGen** [comment]
I know this issue is closed, but I can't quite figure out what the fix was finally. Is it within mei_encoding? Is that where I can test it?

**Comment by jackyyzhang03** [comment]
Yes, the fix was done in MEI encoding. Custos should now take the pitch of the neume after the next clef (as long as it is close enough).
