### ISSUE TITLE
3 OMR functions performing less well (May to October comparison) - 2/3 PITCH FINDING

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#944]
This is one of three issues related to a significant change in OMR performance between May and October 2022. 
1/3 Bounding boxes: https://github.com/DDMAL/Rodan/issues/802
3/3 Syllables: https://github.com/DDMAL/Rodan/issues/945

This issue is about pitch finding.

I've noticed that in recent OMR runs, the pitches are almost systematically too low. To test this theory, I ran Einsie folio 129r yesterday (October 27) to compare the result to my initial processing of the same folio on May 30. Here's a comparison of the results with the neume highlight (I only resized the staves to make the pitches easy to see; I made no other changes):

<img width="1415" alt="Neumes comparison 129r" src="https://user-images.githubusercontent.com/83373378/198675657-b772e31c-5bcf-4276-98c7-1cdd2e71b82a.png">

You can see that, indeed, the pitches are generally more off in the recent folio. There also appear to be more glyphs in the "gutter."

These are the two MEI files, as well as the original folio image:
[129r now.mei.zip](https://github.com/DDMAL/Rodan/files/9889843/129r.now.mei.zip)
[129r then.mei.zip](https://github.com/DDMAL/Rodan/files/9889844/129r.then.mei.zip)
![Einsiedeln__Stiftsbibliothek__Codex_611_129r](https://user-images.githubusercontent.com/83373378/198676093-ec6b8ac8-998f-4280-be78-224beb9c9065.jpg)

**Comment by MrMondrian** [comment]
Looking closely at the misplaced pitches, they seem to all be exactly one whole tone too low or too high. Could this actually be a staff finding issue? When heuristic pitch finding was [brought into the rodan repo](https://github.com/DDMAL/Rodan/commit/b8ef4fe70f5b7ee0313d516bfd81ee40bf793a7a), it seems that Kemal took from develop instead of master. This means that [this hotfix](https://github.com/DDMAL/heuristic_pitch_finding/commit/c8c37853c0305524a9a887e89c63ada5cb76eea7) that Noah (the main author of heuristic pitch finding and staff finding) never made its may into Rodan. This commit rewrites a significant chunk of staff finding, and is what would've been running on Rodan production prior to last summer.

**Comment by MrMondrian** [comment]
Part of the issue may be the new [classes.txt](https://github.com/DDMAL/e2e-omr-resources/blob/main/music_symbol_recognition/classes.txt) being used int IC. The classes include not only small neume component, but larger connected neume components. Feeding these bigger neumes into heuristic pitch finding could mess up the center of mass calculations. In the folio, notice that most pitches are guessed to be too low, but for the larger connected neume components like scandicuses, they are estimated to be too high. Mei encoding assumes pitch finding returns the first pitch, but instead it finds the center of mass which would be the middle pitch raising the whole neume component up by one pitch.

**Comment by MrMondrian** [comment]
There were two sources for this issue. One was introduced in the move from py2 to py3. When finding the average punctum size, only glyphs with the punctum id were considered. However since gamera returns ascii bytes, the comparison from the id to "punctum" would always return false.

Secondly, the math for finding the position of the pitch based on the line it is closest to and if it is in a line or space was just wrong. I updated the formula to be correct. I also updated the comments in the code to accurately explain the logic of the pitch positions.

Fixes can be found in [this PR](https://github.com/DDMAL/Rodan/pull/974)

**Comment by MrMondrian** [comment]
I wouldn't know the answer to that but my changes should make this not happen if I did everything correctly

**Comment by annamorphism** [comment]
that's really a question for @JoyfulGen who has all the straight-from-OMR files...but looking at the uploaded files, thee last ones with line 4 are from June 2 2022...then there was a gap in creating MEI files that whole summer, so the next datapoint isn't until Oct.20 2022, by which time both "line=4.5" and "lines=4" start appearing (also the encoding in the header switches to "utf8" rather than "UTF-8"--makes the files easy to spot!)

**Comment by annamorphism** [comment]
this may no longer be a relevant observation, but the pitches in the gutter are interestingly off. In the older, better, file, the first ones (in green) are labeled ddc; in the newer one they are bab (so the pitches identified differ by about a third), and the MEI is such that the staff break happens later , so the first two end up glued to the previous staff (with Neon trying to keep their x-coordinates the same). meanwhile the previous ad and fd  neumes are the same.

**Comment by MrMondrian** [comment]
I pulled the [docker image from May 31 2022](https://hub.docker.com/layers/ddmal/rodan-python3-celery/v2.0.0/images/sha256-83a4372beb27fb4097f49c5b6e5b2f80378766ebfef5bc0b01176bf16a6f93b6?context=explore). The buggy code was in that image too. I think maybe pitch finding was always buggy but it was being accounted for by some other part of the code.

**Comment by MrMondrian** [comment]
Also, if you look closely, the staff lines are slightly different between the two.

**Comment by annamorphism** [comment]
> Also, if you look closely, the staff lines are slightly different between the two.

Totally--although I think the newer image/older code might actually be slightly closer on the whole, or at least comes out about equally accurate (it catches the angle of staffs 1 and 8 a bit better, but is a little worse on 3 and 5).

**Comment by MrMondrian** [comment]
Further improvements and explanations can be found in https://github.com/DDMAL/Rodan/pull/998

**Comment by MrMondrian** [comment]
@JoyfulGen have you had a chance to test the changes? If so, can we close this issue?

**Comment by JoyfulGen** [comment]
@MrMondrian so sorry for taking a while--I've just run an e2e of Einsie folio 195v to compare it with the one I did in early December. Looking specifically at pitches, I'm not seeing any difference between the two. It also seems that most of the obliques aren't rendering right anymore.

<img width="1158" alt="195 old vs new" src="https://github.com/DDMAL/Rodan/assets/83373378/055c2b51-1a49-4301-bf03-608e31efea2e">

I'm worried I'm doing something wrong though... Is it ok that I'm using the same resources (training data etc.) as before?

These are the two MEI files:
[195v new!.mei.zip](https://github.com/DDMAL/Rodan/files/12173087/195v.new.mei.zip)
[195v old.mei.zip](https://github.com/DDMAL/Rodan/files/12173090/195v.old.mei.zip)

**Comment by JoyfulGen** [comment]
**UPDATE**: please disregard the above data, turns out I was using the wrong model and also not all changes were pushed to production, so I shall test again and return.

**Comment by JoyfulGen** [comment]
**NEW UPDATE**: I've run the original folio, 129r, again on staging with the proper text alignment model (Salzinnes_StGallen, for reference) AND IT WORKS. Pitches are as correct as they used to be and it's so beautiful it brings a tear to my eye. Behold:
<img width="951" alt="129r new!" src="https://github.com/DDMAL/Rodan/assets/83373378/6de1b391-3e8b-4ec7-8ff4-1bcf744f3b24">
@MrMondrian you can close the issue as far as I'm concerned!
